# Use the Flutter recommended base lints
include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false # Prevent unintended type casting
    implicit-dynamic: false # Require explicit dynamic types

linter:
  rules:
    # General code quality
    always_declare_return_types: true
    always_specify_types: false
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_expression_function_bodies: false
    avoid_print: true
    unnecessary_this: true

    # Flutter widget best practices
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true

    # Null-safety / readability
    avoid_init_to_null: true
    avoid_dynamic_calls: true
    prefer_is_empty: true
